name: Docker Deployment
on:
  push:
    branches:
      - deploy/*
<<<<<<< HEAD
=======
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - deploy/*
    paths:
      - 'backend/**'
>>>>>>> main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
<<<<<<< HEAD
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sysadmin-back:1.0.${{ github.run_number }}

=======
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sysadmin-back:1.0.${{ github.run_number }}
>>>>>>> main
